[[term]]
term = "プリンセス・ハニートラップ"
translation = "公主·甜蜜陷阱"

[[term]]
term = "ソフィア"
translation = "索菲娅"

[[term]]
term = "ステラ"
translation = "斯黛拉"

[[term]]
term = "シャナ"
translation = "夏娜"

[[term]]
term = "ダンタリオン"
translation = "但他林"
