[[term]]
term = "ぼくとサキュバス"
translation = "我与魅魔"

[[term]]
term = "ミレーヌ"
translation = "米蕾妮"

[[term]]
term = "リリス"
translation = "莉莉丝"

[[term]]
term = "シズク"
translation = "雫"

[[term]]
term = "マナ"
translation = "魔力"
