//! `plugins.js` 外壳的唯一结构解析契约。
//!
//! 提取与写回可以各自使用适合本域的 JSON 解码器，但声明、合法前缀、
//! assignment、终止符和根类型必须共享同一组结构化事实。

use std::fmt;

const PLUGINS_DECLARATION: &str = "var $plugins";

/// `plugins.js` 外壳中已经定位的正文及需逐字保留的前缀。
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct PluginsEnvelope<'a> {
    prefix: &'a str,
    json: &'a str,
}

impl<'a> PluginsEnvelope<'a> {
    pub(crate) const fn prefix(self) -> &'a str {
        self.prefix
    }

    pub(crate) const fn json(self) -> &'a str {
        self.json
    }
}

/// `plugins.js` 外壳失败的稳定结构化事实。
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum PluginsEnvelopeFailure {
    Declaration,
    Prefix,
    Assignment,
    Terminator,
    RootType,
}

impl fmt::Display for PluginsEnvelopeFailure {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::Declaration => "缺少 `var $plugins` 声明",
            Self::Prefix => "声明前缀不是空白或行注释",
            Self::Assignment => "声明后缺少 `=` assignment",
            Self::Terminator => "assignment 缺少结尾分号",
            Self::RootType => "assignment 的 JSON 根不是数组",
        })
    }
}

pub(crate) fn parse_plugins_envelope(
    text: &str,
) -> Result<PluginsEnvelope<'_>, PluginsEnvelopeFailure> {
    let declaration_offset = plugins_declaration_offset(text)?;
    let prefix = &text[..declaration_offset];
    let assignment = &text[declaration_offset + PLUGINS_DECLARATION.len()..];
    let Some(json_with_terminator) = assignment.trim_start().strip_prefix('=') else {
        return Err(PluginsEnvelopeFailure::Assignment);
    };
    let Some(json) = json_with_terminator.trim().strip_suffix(';') else {
        return Err(PluginsEnvelopeFailure::Terminator);
    };
    Ok(PluginsEnvelope {
        prefix,
        json: json.trim(),
    })
}

fn plugins_declaration_offset(text: &str) -> Result<usize, PluginsEnvelopeFailure> {
    let mut line_start = 0usize;
    for raw_line in text.split_inclusive('\n') {
        let line = raw_line.strip_suffix('\n').unwrap_or(raw_line);
        let trimmed = line.trim_start();
        if trimmed.starts_with(PLUGINS_DECLARATION) {
            return Ok(line_start + line.len() - trimmed.len());
        }
        if trimmed.trim().is_empty() || trimmed.starts_with("//") {
            line_start += raw_line.len();
            continue;
        }
        return Err(if text[line_start..].contains(PLUGINS_DECLARATION) {
            PluginsEnvelopeFailure::Prefix
        } else {
            PluginsEnvelopeFailure::Declaration
        });
    }
    Err(PluginsEnvelopeFailure::Declaration)
}

pub(crate) fn validate_plugins_root_is_array(is_array: bool) -> Result<(), PluginsEnvelopeFailure> {
    is_array
        .then_some(())
        .ok_or(PluginsEnvelopeFailure::RootType)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preserves_the_legal_prefix_byte_for_byte() {
        let prefix = "// Generated by RPG Maker.\r\n// 保留  \r\n\r\n";
        let text = format!("{prefix}var $plugins = [];\r\n");
        let envelope = parse_plugins_envelope(&text).expect("合法外壳应解析");

        assert_eq!(envelope.prefix().as_bytes(), prefix.as_bytes());
        assert_eq!(envelope.json(), "[]");
    }

    #[test]
    fn ignores_declaration_text_inside_a_legal_line_comment() {
        let prefix = "// var $plugins = [\"not the declaration\"];\r\n// generated\r\n";
        let text = format!("{prefix}  var $plugins = [];");
        let envelope = parse_plugins_envelope(&text).expect("注释正文不能遮蔽真实声明");

        assert_eq!(envelope.prefix(), format!("{prefix}  "));
        assert_eq!(envelope.json(), "[]");
    }

    #[test]
    fn classifies_each_envelope_failure() {
        for (text, expected) in [
            ("const plugins = [];", PluginsEnvelopeFailure::Declaration),
            (
                "/* block */\nvar $plugins = [];",
                PluginsEnvelopeFailure::Prefix,
            ),
            ("var $plugins [];", PluginsEnvelopeFailure::Assignment),
            ("var $plugins = []", PluginsEnvelopeFailure::Terminator),
        ] {
            assert_eq!(parse_plugins_envelope(text), Err(expected));
        }
        assert_eq!(
            validate_plugins_root_is_array(false),
            Err(PluginsEnvelopeFailure::RootType)
        );
    }
}
