[[term]]
term = "サキュバスアカデミア"
translation = "魅魔学院"

[[term]]
term = "アルマエルマ"
translation = "阿尔玛·艾尔玛"

[[term]]
term = "エルフリーデ"
translation = "艾尔芙莉德"

[[term]]
term = "綾瀬 歩夢"
translation = "绫濑步梦"

[[term]]
term = "サキュバスアーツ"
translation = "魅魔秘技"
