[[rule]]
order = 'preserve'
pattern = '\\SE\[[^]]+\]'

[[rule]]
scopes = ['event_dialogue', 'event_choices']
order = 'preserve'
pattern = '<msg>(?<text>.*?)</msg>'

[[rule]]
scopes = [
  'database_entry',
  'system',
  'map',
  'event_scrolling_text',
  'event_command',
  'plugin_parameter',
]
order = 'preserve'
pattern = '\{icon:[0-9]+\}'
